import Head from 'next/head'
import Layout from '../components/Layout'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        npm install @mui/material @emotion/react @emotion/styled
      </Head>
      <Layout>
        <div>
          <h3>Welcome to my folio</h3>
          
          {/* <Project /> */}

        </div>
      </Layout>
    </div>
  )
}
